export const ERROR_CODES = {
  // Domain errors
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_VERIFIED: 'USER_NOT_VERIFIED',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  PASSWORD_POLICY_VIOLATION: 'PASSWORD_POLICY_VIOLATION',

  // Infrastructure errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  CACHE_ERROR: 'CACHE_ERROR',
  EMAIL_SERVICE_ERROR: 'EMAIL_SERVICE_ERROR'
} as const;
