# command line
# (Windows) docker compose up Auth-DB -d
# (ubuntu) docker-compose up Auth-DB
version: '3.8'
services:
  Auth-DB:
    image: postgres:13
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:5432'
    env_file:
      - .env

